// search
export const ADD_RESULTS = 'ADD_RESULTS';
export const TERMINATE_SEARCH = 'TERMINATE_SEARCH';

export const WALL_POSTS_SEARCH_START = 'WALL_POSTS_SEARCH_START';
export const WALL_POSTS_SEARCH_END = 'WALL_POSTS_SEARCH_END';

export const REQUEST_START = 'REQUEST_START';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAIL = 'REQUEST_FAIL';

// auth
export const SAVE_AUTH_DATA = 'SAVE_AUTH_DATA';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SIGN_OUT = 'SIGN_OUT';
export const NO_TOKEN = 'NO_TOKEN';
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
export const REDIRECT_TO_AUTH = 'REDIRECT_TO_AUTH';
export const OFFER_AUTH_REDIRECT = 'OFFER_AUTH_REDIRECT';
