// TODO: try to place next to middleware
// search middleware
export const SEARCH_SET_OFFSET = 'SEARCH_SET_OFFSET';
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_END = 'SEARCH_END';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const TERMINATE_SEARCH = 'TERMINATE_SEARCH'; // TODO: OFFSET_SEARCH_TERMINATE

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_REQUEST_SUCCESS = 'SEARCH_REQUEST_SUCCESS';
export const SEARCH_REQUEST_FAIL = 'SEARCH_REQUEST_FAIL';
export const SEARCH_REQUEST_REFUSE = 'SEARCH_REQUEST_REFUSE';

// posts
export const POSTS_RECEIVED = 'POSTS_RECEIVED';
export const SET_POSTS_SORT_ORDER = 'SET_POSTS_SORT_ORDER';
export const SET_POSTS_FILTER_TEXT = 'SET_POSTS_FILTER_TEXT';

export const FETCH_WALL_POSTS_REQUEST = 'FETCH_WALL_POSTS_REQUEST';
export const FETCH_WALL_POSTS_FAIL = 'FETCH_WALL_POSTS_FAIL';

// auth
export const SAVE_AUTH_DATA = 'SAVE_AUTH_DATA';

export const LOGIN = 'LOGIN';
export const LOGIN_CANCEL = 'LOGIN_CANCEL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SIGN_OUT = 'SIGN_OUT';
export const NO_VALID_TOKEN = 'NO_VALID_TOKEN';

export const OFFER_AUTH = 'OFFER_AUTH';
export const REJECT_AUTH_OFFER = 'REJECT_AUTH_OFFER';
